graph_construction_share:
  graph_type: 'constituency'
  root_dir: null
  topology_subdir: 'ConstituencyGraph'
  share_vocab: true
  thread_number: 4
  port: 9000
  timeout: 15000

graph_construction_private:
  merge_strategy: 'tailhead'
  sequential_link: true
  bisequential_link: true

node_embedding:
  input_size: 300
  hidden_size: 300
  word_dropout: 0.0
  rnn_dropout: 0.0
  fix_bert_emb: false
  fix_word_emb: false
  embedding_style:
    single_token_item: true
    emb_strategy: "w2v_bilstm"
    num_rnn_layers: 1
    bert_model_name: null
    bert_lower_case: null
