graph_construction_share:
  graph_type: 'dependency'
  root_dir: null
  topology_subdir: 'DependencyGraph'
  share_vocab: true
  thread_number: 4
  port: 9000
  timeout: 15000

graph_construction_private:
  edge_strategy: 'homogeneous'
  merge_strategy: 'tailhead'
  sequential_link: true
  as_node: false
  # nlp_tools_args: # we use stanford corenlp as default nlp tools, please refer to ``https://stanfordnlp.github.io/CoreNLP/tokenize.html``
  #   name: "stanfordcorenlp"
  #   tokenizer_args:
  #     whitespace: true # If set to true, separates words only when whitespace is encountered.
  #   normalize_parentheses: false # Whether to map round parentheses to -LRB-, -RRB-, as in the Penn Treebank
  #   normalize_other_brackets: false # Whether to map other common bracket characters to -LCB-, -LRB-, -RCB-, -RRB-, roughly as in the Penn Treebank
  #   split_hyphenated: false # Whether or not to tokenize hyphenated words as several tokens (“school” “-“ “aged”, “frog” “-“ “lipped”)
  #   is_oneSentence: true # Whether to regard the inputs as one sentence
  #   port: 9000
  #   timeout: 15000


node_embedding:
  input_size: 300
  hidden_size: 300
  word_dropout: 0.0
  rnn_dropout: 0.0
  fix_bert_emb: false
  fix_word_emb: false
  embedding_style:
    single_token_item: true
    emb_strategy: "w2v_bilstm"
    num_rnn_layers: 1
    bert_model_name: null
    bert_lower_case: null
