graph_embedding_share:
  num_layers: 1
  input_size: 300
  hidden_size: 300
  output_size: 300
  direction_option: "undirected"
  feat_drop: 0.0

graph_embedding_private:
  gcn_norm: 'both'
  weight: true
  bias: true
  activation: null
  allow_zero_in_degree: false
  use_edge_weight: false
